-- Add parent_narrative field to InjuryReports table
ALTER TABLE "InjuryReports"
ADD COLUMN IF NOT EXISTS parent_narrative TEXT;

-- Add comment explaining the purpose of this field
COMMENT ON COLUMN "InjuryReports".parent_narrative IS 'Parent-friendly narrative generated by the combined n8n workflow';

-- Note: The memo_content field is kept for backward compatibility with existing records
